name: CMCA
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.8
  - pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - torchvision=0.14.1=py38_cu116
  - torchaudio=0.13.1=py38_cu116
  - cudatoolkit=11.6
  - tqdm
  - regex
  - ftfy
  - pip:
      - pytorch-lightning==1.7.3
      - torchmetrics==0.9.3